### ISSUE TITLE
Unhandled promise rejection when calling an auth provider route that's not configured

### ISSUE THREAD

**Issue by JAertgeerts** [jaumard/trailpack-passport#124]
When calling:
api/v1/auth/google/
while google as a strategy is not defined, results into:
(node:8763) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): /
(node:8763) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero
exit code.

Local is also not a defined strategy.
https://github.com/jaumard/trailpack-passport/blob/master/api/services/PassportService.js#L71
is assuming it is with not handling an alternative scenario than https://github.com/jaumard/trailpack-passport/blob/master/api/services/PassportService.js#L89 

Even if I define local, I still get the UnhandledPromiseRejectionWarning and my call times out.

**Comment by jaumard** [comment]
Hi :)

So what is the use case exactly here ? You try to access api/v1/auth/{strategy}/ with a strategy that doesn't exist ? I just try and I get a 404 error on my project.
I didn't try to disable local strategy but I'll later, maybe there a problem there you're right as I use it as fallback (didn't think about a use case without local strategy at all ^^). But for your `api/v1/auth/google/` I don't think the problem come from this module, maybe it come from another trailpack that is called instead of this one.

**Comment by jaumard** [comment]
If you have some repo example (or can make one) that reproduce this error that can be useful because I can't reproduce this, maybe it have to depends of web server and ORM you choose

**Comment by JAertgeerts** [comment]
https://github.com/JAertgeerts/trails-example

**Comment by JAertgeerts** [comment]
I'll add some more context to this issue later, not able to do so now.

**Comment by jaumard** [comment]
No problem I'll make some test with your repo see if I can reproduce :) thanks!

**Comment by jaumard** [comment]
Can you please test with master and let me know if it's fix now ?

**Comment by JAertgeerts** [comment]
That does the trick! Thanks @jaumard

**Comment by JAertgeerts** [comment]
However, when I go to a route that is successful:
```
2017-03-06T07:49:27.092845+00:00 app[web.1]: [31merror[39m:  TypeError: Cannot read property 'catch' of undefined
2017-03-06T07:49:27.092863+00:00 app[web.1]:     at AuthController.provider (/app/node_modules/trailpack-passport/api/controllers/AuthController.js:9:78)
2017-03-06T07:49:27.092865+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-03-06T07:49:27.092865+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2017-03-06T07:49:27.092866+00:00 app[web.1]:     at args.(anonymous function) (/app/node_modules/trailpack-express/lib/utils.js:21:13)
2017-03-06T07:49:27.092867+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-03-06T07:49:27.092867+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2017-03-06T07:49:27.092868+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2017-03-06T07:49:27.092869+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-03-06T07:49:27.092870+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:281:22
2017-03-06T07:49:27.092871+00:00 app[web.1]:     at param (/app/node_modules/express/lib/router/index.js:354:14)
2017-03-06T07:49:27.092871+00:00 app[web.1]:     at param (/app/node_modules/express/lib/router/index.js:365:14)
2017-03-06T07:49:27.092872+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
2017-03-06T07:49:27.092872+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2017-03-06T07:49:27.092873+00:00 app[web.1]:     at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
2017-03-06T07:49:27.092873+00:00 app[web.1]:     at router (/app/node_modules/express/lib/router/index.js:47:12)
2017-03-06T07:49:27.092874+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-03-06T07:49:27.096853+00:00 app[web.1]: Error: Can't set headers after they are sent.
2017-03-06T07:49:27.096855+00:00 app[web.1]:     at ServerResponse.setHeader (_http_outgoing.js:371:11)
2017-03-06T07:49:27.096855+00:00 app[web.1]:     at ServerResponse.header (/app/node_modules/express/lib/response.js:725:10)
2017-03-06T07:49:27.096856+00:00 app[web.1]:     at ServerResponse.contentType (/app/node_modules/express/lib/response.js:558:15)
2017-03-06T07:49:27.096856+00:00 app[web.1]:     at 500 (/app/node_modules/trailpack-express/config/web.js:128:15)
2017-03-06T07:49:27.096857+00:00 app[web.1]:     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
2017-03-06T07:49:27.096857+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
2017-03-06T07:49:27.096858+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:7
2017-03-06T07:49:27.096858+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2017-03-06T07:49:27.096859+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2017-03-06T07:49:27.096859+00:00 app[web.1]:     at expressErrorHandler (/app/node_modules/@risingstack/trace/lib/instrumentations/express.js:21:5)
2017-03-06T07:49:27.096860+00:00 app[web.1]:     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
2017-03-06T07:49:27.096860+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
2017-03-06T07:49:27.096861+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:7
2017-03-06T07:49:27.096861+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2017-03-06T07:49:27.096861+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2017-03-06T07:49:27.096862+00:00 app[web.1]:     at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
```

**Comment by jaumard** [comment]
You're right... I'll fix that asap

**Comment by jaumard** [comment]
Should work now, I miss to return a promise when it's all good sorry

**Comment by JAertgeerts** [comment]
Fixed, awesome & thanks for the quick commit.
