### ISSUE TITLE
Cannot start trails app when I use trailpack-passport

### ISSUE THREAD

**Issue by nosnibor89** [jaumard/trailpack-passport#166]
I'm trying to use trailpack-passpor but when I import it to config/main.js and try to start the app I get this error:

```
error:
 TypeError: Cannot read property 'toLowerCase' of undefined
    at Schema.objectAttribute (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\waterline\lib\waterline\core\schema.js:168:25)
    at F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\waterline\lib\waterline\core\schema.js:58:29
    at Array.forEach (native)
    at Schema.initialize (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\waterline\lib\waterline\core\schema.js:56:22)
    at child.Core._initialize (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\waterline\lib\waterline\core\index.js:89:16)
    at child.module.exports (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\waterline\lib\waterline\core\index.js:50:20)
    at child.module.exports (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\waterline\lib\waterline\collection\index.js:44:8)
    at new child (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\waterline\lib\waterline\utils\extend.js:17:40)
    at initialize (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\waterline\lib\waterline\collection\loader.js:37:10)
    at loadCollection (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\waterline\lib\waterline.js:109:29)
    at F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\async\lib\async.js:233:13)
    at Object.async.forEach.async.each (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\async\lib\async.js:209:22)
    at Array.loadCollections (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\waterline\lib\waterline.js:122:13)
    at F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\async\lib\async.js:596:38
    at _arrayEach (F:\Development\ShareableInn\Beelivery\Projects\beelivery-api\node_modules\async\lib\async.js:85:13)
error: The application did not boot successfully.
error: Try increasing the loglevel to "debug" to learn more
```

**Comment by jaumard** [comment]
Did you follow the readme instructions ? What does your model look like ? Don't hesitate to look at the example https://github.com/jaumard/trails-example-express to see the configuration and how model should be configured

**Comment by nosnibor89** [comment]
Yeah, I followed the guide and the example(In fact, I could not run it).  
This is my user model, the only model I have.

```
"use strict";

const Model = require("trails/model");

/**
 * @module User
 * @description Beelivery&#39;s users
 */
module.exports = class User extends Model {
  static config() {}

  static schema() {
    return {
      // Props
      id: {
        primaryKey: true
      },
      firstName: {
        type: "string"
      },
      lastName: {
        type: "string"
      },
      profilePicture: {
        type: "string"
      },
      email: {
        type: "string"
      },
      emailVerified: {
        type: "boolean"
      },
      phone: {
        type: "string"
      },
      phone2: {
        type: "string"
      },
      address: {
        type: "text"
      },
      referralCode: {
        type: "string"
      }
    };
  }
};

```

**Comment by jaumard** [comment]
Check the user model of the example, those fields are mandatory on your model in order to work. I miss to write this part on the readme. I'll add it.

**Comment by jaumard** [comment]
Here is maybe a more complete example where I use trailpack-passport and trailpack-acl where both have a User model, it's for sequelize not waterline but it may show you how to do it https://github.com/mylisabox/lisa-box/blob/master/api/models/User.js basically I retrieve config/schema from passport User model and merge it with fields I want. If you don't do that the trailpack will try to access fields that doesn't exist

**Comment by nosnibor89** [comment]
Thanks @jaumard , you can close these already. The User model configuration really helped me.

**Comment by jaumard** [comment]
Cool glad you made it :)
