### ISSUE TITLE
Error: No strategies found at config.passport.strategies

### ISSUE THREAD

**Issue by connor11528** [jaumard/trailpack-passport#60]
I am clearly missing something. I created the **config/passport.js** file but get this error:

```
error: 
 Error: No strategies found at config.passport.strategies !
    at PassportTrailpack.validate (/Users/connorleech/Projects/trails-tutorial/node_modules/trailpack-passport/index.js:22:29)
    at app.after.then (/Users/connorleech/Projects/trails-tutorial/node_modules/trails/lib/trailpack.js:68:26)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3
```

Also copied and pasted in the code into **config/session.js** (like in the [example](https://github.com/jaumard/trails-example-express/blob/bf02f20a206153e5a8c9cce4bfaf9814e8c8ea19/config/session.js)) but error persists

**Comment by jaumard** [comment]
The example is not up to date with last version of the module. Now `config/session.js` have to be used to configure express sessions only and `config/passport.js ` to configure this module. 
You have an example here https://github.com/jaumard/trailpack-passport/blob/master/archetype/config/passport.js but be sure to import your `config/passport.js` into `config/index.js`.
If you still have problem show me the content of your config file :)

**Comment by connor11528** [comment]
Awesome thank you! I had to link to it in `config/index.js`.
